before_script: ~
env: 
  - DJANGO_VERSION=1.11.2
install: 
  - "pip install -r requirements.txt"
  - "pip install django==$DJANGO_VERSION"
language: python
python: 
  - "3.5"
  - "3.6"
script: 
  - "python manage.py test"
services: ~
notifications:
   email: false
